// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ToDoList.Models
{
    public partial class TodoItems
    {
        public int IdTodo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? IdUser { get; set; }

        public virtual Users IdUserNavigation { get; set; }
    }
}